### ISSUE TITLE
TypeError when using "import starster"

### ISSUE THREAD

**Issue by abdinal1** [phuang1024/Starst3r#1]
I get following error after installing the package via pip install, by just using import starster:

Warning, cannot find cuda-compiled version of RoPE2D, using a slow pytorch version instead
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 import starster
      3 device = "cuda"
      5 # List of paths to images

File ~\Anaconda3\lib\site-packages\starster\__init__.py:3
      1 from mast3r.model import AsymmetricMASt3R as Mast3rModel
----> 3 from .image import *
      4 from .reconstruct import *
      5 from .scene import *

File ~\Anaconda3\lib\site-packages\starster\image.py:39
     35             pairs.append((pairs[i][1], pairs[i][0]))
     36     return pairs
---> 39 def process_image(img: np.ndarray | torch.Tensor, size: int) -> torch.Tensor:
     40     """
     41     Preprocess image to model requirements.
     42 
   (...)
     47     :return: Tensor, shape (C,H,W), dtype float32
     48     """
     49     new_size = [int(x * size / max(img.shape[1:])) for x in img.shape[1:]]

TypeError: unsupported operand type(s) for |: 'type' and 'torch._C._TensorMeta'

**Comment by abdinal1** [comment]
Solved by upgrading python to atleast 3.10

**Comment by phuang1024** [comment]
Hi there,

The RoPE2D warning comes from croco (https://github.com/naver/croco) which is a submodule.

To use the cuda RoPE, a shell command must be run inplace in the croco installation.

As Naver did not release croco on PyPI, the compilation step isn't implemented when installing from pip.

The code will still work, but is a bit slower. The performance decrease happens when running inference on the Mast3r model.

An unrelated error is the type hints. As you noted, the Starst3r library requires Python >= 3.10 for type hints.
